version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wb-api-test
    container_name: wb-api-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: sql.freedb.tech
      DB_PORT: 3306
      DB_DATABASE: freedb_testdbapp
      DB_USERNAME: freedb_qwertyu
      DB_PASSWORD: '3xXG3FkxX&3P*$E'
  #  command: php artisan serve --host=0.0.0.0 --port=8000

  octane:
    build:
      context: .
      dockerfile: Dockerfile
    image: wb-api-test
    container_name: wb-api-octane
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9001:8000"
    env_file:
      - .env
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000
